spring:
  application:
    name: sql-injection-spring
  datasource:
    url: jdbc:mysql://localhost:3306/sql_injection_spring?serverTimezone=Asia/Seoul
    username: root
    password: root12
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug